# run the testsuite on travis-ci.com
---
# versions to run on
env:
  - PG_SUPPORTED_VERSIONS=9.5
  - PG_SUPPORTED_VERSIONS=9.6
  - PG_SUPPORTED_VERSIONS=10
  - PG_SUPPORTED_VERSIONS=11
  - PG_SUPPORTED_VERSIONS=12
  - PG_SUPPORTED_VERSIONS=13

language: C
dist: bionic

before_install:
  - sudo apt-get update -qq

install:
  # upgrade postgresql-common for new apt.postgresql.org.sh
  - sudo apt-get install -y postgresql-common
  - sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -p -v $PG_SUPPORTED_VERSIONS -i
  - sudo apt-get install -y postgresql-contrib-$PG_SUPPORTED_VERSIONS

script:
  - make
  - sudo make install
  - pg_virtualenv make installcheck
  - if test -s regression.diffs; then cat regression.diffs; fi
